### PR TITLE
Added more features and tests

### PR DESCRIPTION
**Pull request by pires**
- Implemented `Count`, `Has`, `GetAndRemove` and `IsEmpty` functions.
- Added tests but have been unable to get them to work. [`gotemplate` has them](https://github.com/ncw/gotemplate/blob/master/set/set_test.go). Could it be something with Go 1.5?

### CODE REVIEW

**Comment by pires** [comment]
@sreis the purpose of `concurrent_test.go` is to test the template code. Just like https://github.com/ncw/gotemplate/blob/master/set/set_test.go

**Comment by sreis** [comment]
@pires If you notice after you run `go generate` those lines are deleted. As they should be. 

If you remove those lines from the template and run `go generate` you get the same result you posted. 

My approach is to have abstract templates in the package. Tests will be on another directory. I'll implement something later today.

**Comment by pires** [comment]
Addressed your concerns but am unable to get tests to work. Could it be something with the locks?

**Comment by pires** [comment]
Tests have been fixed.

```
$ make test
go test -v ./...
?   	concurrentmap	[no test files]
=== RUN   TestNewStringIntMapConcurrentMap
--- PASS: TestNewStringIntMapConcurrentMap (0.00s)
=== RUN   TestConcurrentMapSet
--- PASS: TestConcurrentMapSet (0.00s)
=== RUN   TestConcurrentMapGet
--- PASS: TestConcurrentMapGet (0.00s)
=== RUN   TestConcurrentMapRemove
--- PASS: TestConcurrentMapRemove (0.00s)
=== RUN   TestConcurrentMapGetAndRemove
--- PASS: TestConcurrentMapGetAndRemove (0.00s)
=== RUN   TestConcurrentMapCount
--- PASS: TestConcurrentMapCount (0.01s)
=== RUN   TestConcurrentMapHas
--- PASS: TestConcurrentMapHas (0.00s)
PASS
ok  	tests	0.019s
```

**Comment by pires** [comment]
```
$ make
go generate -v -x ./src/tests
src/tests/concurrentmap_test.go
gotemplate concurrentmap StringIntMap(string, int)
2015/08/15 20:04:15 Substituting "concurrentmap" with StringIntMap(string,int) into package tests
2015/08/15 20:04:15 Written 'gotemplate_StringIntMap.go'
src/tests/gotemplate_StringIntMap.go
go build -v ./src/tests
tests
go test -v ./src/tests
=== RUN   TestNewStringIntMapConcurrentMap
--- PASS: TestNewStringIntMapConcurrentMap (0.00s)
=== RUN   TestConcurrentMapSet
--- PASS: TestConcurrentMapSet (0.00s)
=== RUN   TestConcurrentMapGet
--- PASS: TestConcurrentMapGet (0.00s)
=== RUN   TestConcurrentMapRemove
--- PASS: TestConcurrentMapRemove (0.00s)
=== RUN   TestConcurrentMapGetAndRemove
--- PASS: TestConcurrentMapGetAndRemove (0.00s)
=== RUN   TestConcurrentMapCount
--- PASS: TestConcurrentMapCount (0.01s)
=== RUN   TestConcurrentMapHas
--- PASS: TestConcurrentMapHas (0.00s)
PASS
ok  	tests	0.021s
```

**Comment by pires** [comment]
```
$ make
go generate -v -x ./tests
tests/concurrentmap_test.go
gotemplate ../concurrentmap StringIntMap(string, int)
2015/08/15 20:50:54 Substituting "../concurrentmap" with StringIntMap(string,int) into package tests
2015/08/15 20:50:54 Written 'gotemplate_StringIntMap.go'
tests/gotemplate_StringIntMap.go
go test -v ./tests
=== RUN   TestNewStringIntMapConcurrentMap
--- PASS: TestNewStringIntMapConcurrentMap (0.00s)
=== RUN   TestConcurrentMapSet
--- PASS: TestConcurrentMapSet (0.00s)
=== RUN   TestConcurrentMapGet
--- PASS: TestConcurrentMapGet (0.00s)
=== RUN   TestConcurrentMapRemove
--- PASS: TestConcurrentMapRemove (0.00s)
=== RUN   TestConcurrentMapGetAndRemove
--- PASS: TestConcurrentMapGetAndRemove (0.00s)
=== RUN   TestConcurrentMapCount
--- PASS: TestConcurrentMapCount (0.01s)
=== RUN   TestConcurrentMapHas
--- PASS: TestConcurrentMapHas (0.00s)
PASS
ok      _/Users/pires/Work/Projects/gotemplates/tests   0.019s
```

**Pull request merged**
